repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        types: [python]
        entry: poetry run isort .
        language: system
        pass_filenames: false
        always_run: true
      - id: black
        name: black
        stages: [commit]
        types: [python]
        entry: poetry run black .
        language: system
        pass_filenames: false
        always_run: true
      - id: flake8
        name: flake8
        stages: [commit]
        types: [python]
        entry: poetry run flake8 .
        language: system
        pass_filenames: false
        always_run: true
        fail_fast: true
      - id: pytest
        name: pytest
        stages: [commit]
        types: [python]
        entry: poetry run pytest
        language: system
        pass_filenames: false
        always_run: true
        fail_fast: true
